version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - fitec_network

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fitec_network  

volumes:
  mysqldata:

networks:
  fitec_network: